name: Build Custom Maple Font

on:
 schedule:
   - cron: '0 */6 * * *'
 workflow_dispatch:

jobs:
 check-and-build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout own repository
       uses: actions/checkout@v4

     - name: Check for new Maple tag
       id: check-tag
       run: |
         LATEST_TAG=$(curl -s https://api.github.com/repos/subframe7536/maple-font/tags | jq -r '.[0].name')
         echo "Latest Maple tag: $LATEST_TAG"
         LATEST_VERSION=$LATEST_TAG

         CURRENT_ARCHIVE=$(curl -s https://api.github.com/repos/${{ github.repository }}/contents/ | jq -r '.[] | select(.name | test("MapleCustom_.*\\.zip")) | .name' | head -n 1)
         if [ -n "$CURRENT_ARCHIVE" ]; then
           CURRENT_VERSION=$(echo $CURRENT_ARCHIVE | sed -E 's/MapleCustom_(.*)\.zip/\1/')
         else
           CURRENT_VERSION=""
         fi

         if [ -z "$CURRENT_VERSION" ] || [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
           echo "NEW_TAG=true" >> $GITHUB_OUTPUT
           echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
         else
           echo "No new version to build."
         fi

     - name: Clone Maple repository
       if: steps.check-tag.outputs.NEW_TAG == 'true'
       run: |
         git clone --depth 1 --branch ${{ steps.check-tag.outputs.LATEST_TAG }} https://github.com/subframe7536/maple-font.git

     - name: Setup Python
       if: steps.check-tag.outputs.NEW_TAG == 'true'
       uses: actions/setup-python@v5
       with:
         python-version: '3.12'
         cache: 'pip'
         cache-dependency-path: './maple-font/requirements.txt'

     - name: Install dependencies
       if: steps.check-tag.outputs.NEW_TAG == 'true'
       working-directory: maple-font
       run: pip install -r requirements.txt

     - name: Remove operator ligatures (++, +++, ==) from feature files
       if: steps.check-tag.outputs.NEW_TAG == 'true'
       working-directory: maple-font
       run: |
         for file in source/features/{regular,italic}.fea; do
             sed -i \
                 -e '/^[[:space:]]*# ++$/,/^[[:space:]]*} plus_plus.liga;$/d' \
                 -e '/^[[:space:]]*# +++$/,/^[[:space:]]*} plus_plus_plus.liga;$/d' \
                 -e '/^[[:space:]]*# ==$/,/^[[:space:]]*} equal_equal.liga;$/d' \
                 "$file"
         done

     - name: Build custom font
       if: steps.check-tag.outputs.NEW_TAG == 'true'
       working-directory: maple-font
       run: python build.py --archive --feat cv01,cv02,cv03,cv34,cv35,cv36,zero --apply-fea-file --no-cn --no-nerd-font

     - name: Create archive
       id: latest-archive
       if: steps.check-tag.outputs.NEW_TAG == 'true'
       run: |
         VERSION=${{ steps.check-tag.outputs.LATEST_TAG }}
         (cd maple-font/fonts && zip -8 -r ../../MapleCustom_${VERSION}.zip TTF-AutoHint TTF)
         echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

     - name: Manage archives
       if: steps.check-tag.outputs.NEW_TAG == 'true'
       run: |
         mkdir -p archive
         if [ -f "MapleCustom_${{ steps.latest-archive.outputs.VERSION }}.zip" ]; then
           mv MapleCustom_${{ steps.latest-archive.outputs.VERSION }}.zip archive/
           cd archive
           ls -t MapleCustom_*.zip | tail -n +10 | xargs rm -f 2>/dev/null
           cd ..
           mv archive/MapleCustom_${{ steps.latest-archive.outputs.VERSION }}.zip ./
         fi

     - name: Cleanup
       if: steps.check-tag.outputs.NEW_TAG == 'true'
       run: rm -rf maple-font

     - name: Commit and push changes
       if: steps.check-tag.outputs.NEW_TAG == 'true'
       run: |
         git config --local user.email "action@github.com"
         git config --local user.name "Github Actions"
         git add .
         git commit -m "Add new Maple custom build ${{ steps.check-tag.outputs.LATEST_TAG }}"
         git push
